### ISSUE TITLE
is there an executable somewhere?

### ISSUE THREAD

**Issue by jeacott1** [AlexandreDoucet/InfinityBike#15]
Hi,
 nice project but I dont see any binary executable anywhere. did I miss it?
also, I have a smart trainer, do you have anything on your roadmap to support bluetooth or ant+ smart trainers? would be a really nice feature.

**Comment by AlexandreDoucet** [comment]
Hi,
There should be a folder called current build in the project that has the .exe. It's compiled for windows. Just a warning, the project is still in the early phase so there might be bugs and unfinished features.

Let me know if it doesn't work for you.

As for the roadmap, the project is on hold for now so no new features will be added in the near future. We are interested in returning to it once life permits it so I will take note of your suggestion for the future. 

Alex

**Comment by jeacott1** [comment]
oh!
 perhaps you should consider putting your binaries in the github releases section - adding them to your git repo is only going to make it unnecessarily large going forward.

shame about the roadmap, perhaps I'll take a look myself although I haven't done any c++ is a long time.
Cheers.

**Comment by AlexandreDoucet** [comment]
Thank you for the suggestion.

I will take a look at updating the release section. We are still experimenting with diferent things and since alot of it is still unfinished and not very polished, I might hold off a while before calling the .exe an official release.

I have plans to return to infinity bike in the near future and rework alot of things including streamlining how different devices could be added to the project as a whole. 

If you have any inputs feel free to point them out, any feedback is going to be very usefull to us.

**Comment by jeacott1** [comment]
you can mark it a draft release if that helps.
